import pygame as pg

# Window
GAME_NAME = "Pong"
MAX_WINDOW_SIZE = (1920,1080)

# Colors
BACKGROUND_COLOR = "black"
PLAYER_COLOR = "white"
BALL_COLOR = "white"
BOT_COLOR = "white"
WALL_COLOR = "white"

# Time
MAX_FPS = 144
TIME_STEP = 5

# Player
PLAYER_SIZE = (MAX_WINDOW_SIZE[1] // 30, MAX_WINDOW_SIZE[1] //10)
PLAYER_SPEED = 5

# Bot
BOT_SIZE = PLAYER_SIZE
BOT_SPEED = PLAYER_SPEED

# Ball
BALL_SIZE = [MAX_WINDOW_SIZE[1] // 35] * 2

# Walls
MARGIN_SIZE = 16
WALL_SIZE = (MAX_WINDOW_SIZE[0]-MARGIN_SIZE*2, MAX_WINDOW_SIZE[1] // 20)
WALL = pg.Rect(MARGIN_SIZE, MARGIN_SIZE, MAX_WINDOW_SIZE[0] - MARGIN_SIZE*2, MAX_WINDOW_SIZE[1] - MARGIN_SIZE*2)